### ISSUE TITLE
add World Air Quality Index data to Polybar

### ISSUE THREAD

**Issue by x70b1** [x70b1/polybar-scripts#102]
We should rewrite the `World Air Quality Index` of @bojan88 as shell script. 

[The blog post](https://bojandjurdjevic.com/2018/HOWTO-Add-World-Air-Quality-Index-data-to-Polybar/). [The Gist](https://gist.github.com/bojan88/21e54decfd5961cf91d71e54921deee8).

**Comment by x70b1** [comment]
@bojan88 It's done! Thanks a lot! :sunglasses:

**Comment by bojan88** [comment]
:+1: :smile:
