### ISSUE TITLE
Player-mpris-tail: no output when playing some things in vlc

### ISSUE THREAD

**Issue by zjeffer** [x70b1/polybar-scripts#103]
If the media being played by vlc doesn't have an artist or a title (like some movies or tv shows), the only output is the 'stopped icon'. 

I think it would be better if it would display the name of the file being played when the title is empty.

**Comment by x70b1** [comment]
@Cybolic any comments? :cowboy_hat_face:

**Comment by Cybolic** [comment]
Just showing the stopped icon is definitely not the appropriate action for the script; that will get fixed.
As for the text output, I think having another conditional tag for when a tag does _not_ exist could be the solution.

e.g.
`-f '{icon} {:title:{title} }{:-title:{filename}}'`

Would that be a desirable solution?

**Comment by zjeffer** [comment]
That would work great, please add it :)

Thanks for the quick response!
