### ISSUE TITLE
updates-arch-combined only appears on 1 monitor at a time

### ISSUE THREAD

**Issue by zjeffer** [x70b1/polybar-scripts#108]
When using multiple monitors, the module 'updates-arch-combined' only appears on one of them. 

My config file: https://github.com/zjeffer/dotfiles/blob/master/polybar/config

This only happens with updates-arch-combined. All other modules work as intended.

**Comment by x70b1** [comment]
But you use the same bar at two monitors at the same time?

**Comment by zjeffer** [comment]
Yes

**Comment by x70b1** [comment]
Could you change the `exec` line to `exec = echo test`?

**Comment by zjeffer** [comment]
Test displays on both monitors.

**Comment by zjeffer** [comment]
After restarting polybar, the update module always loads about a second after the bar and the other modules. Maybe the update script is slow(er)?

Could it be that this happens to every module that has a long loading time?

**Comment by zjeffer** [comment]
To debug this issue, I set the interval to 10 seconds instead of 600, and now when I refresh, it loads the module on 1 monitor, and after 10 seconds it loads it on the other as well.

**Comment by x70b1** [comment]
The reason why the script does not load instant is that it need to pull the information from the update servers first. This needs more time than just print a cpu usage. 
You could use `$ time /path/to/updates-arch-combined.sh` to count the time.

The problem you have is that the `script` plugin does not run at the same time on different bars. 
But i think its not to achieve.

**Comment by zjeffer** [comment]
So this is more a polybar issue than the particular script? I'll make an issue in the polybar github, closing.

**Comment by zjeffer** [comment]
I have CHECKUPDATES_DB=$(mktemp -d) in the exec line for the updates-arch-combined module, see here: https://github.com/jaagr/polybar/issues/1544#issuecomment-446980388.

The problem is, that this fills the /tmp folder to 100% with `tmp.XXXXXXXXXX' after a few hours of use (X = random letter or number). It adds two folders every time it reloads the module (I set my interval to 100 seconds). 

How do I fix this?

**Comment by patrick96** [comment]
What I would do is:

```dosini
exec = CHECKUPDATES_DB=$(mktemp -d) ~/polybar-scripts/updates-arch-combined.sh && rm -rf "$CHECKUPDATES_DB"
```

The second part deletes the folder again

**Comment by zjeffer** [comment]
That was quick, thanks.

**Comment by zjeffer** [comment]
The rm command doesn't seem to be doing anything. Does this work for you?

**Comment by patrick96** [comment]
Yeah, you're right. This should work though:

```bash
export CHECKUPDATES_DB=$(mktemp -d) && ~/polybar-scripts/updates-arch-combined.sh && rm -rf "$CHECKUPDATES_DB"
```

**Comment by zjeffer** [comment]
It works! Thanks!
