### ISSUE TITLE
Help with system-usb-udev.sh script

### ISSUE THREAD

**Issue by electricsoldier** [x70b1/polybar-scripts#109]
Hello all,

I'm struggling to get this script/module to work as expected: https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/system-usb-udev
I installed the required dependancies. I have created the udev rule, modified it for my user, copied the script to my polybar scripts folder and modified my polybar config to include the new module. At first I was getting a 'permission denied' inside polybar, but that was because I forgot to 'chmod +x' the script. Since doing that, I get nothing at all in polybar, and I can't seem to find any errors anywhere to help troubleshoot. When I run lsblk, I do see my usb in there, same thing for dmesg... but I still don't see anything in polybar. I'm sorry if this is something silly, I'm a little new to all this. Any help would be very much appreciated!

**Comment by x70b1** [comment]
Did you change the PID file path at [line 45](https://github.com/x70b1/polybar-scripts/blob/master/polybar-scripts/system-usb-udev/system-usb-udev.sh#L45)?

**Comment by electricsoldier** [comment]
Hi there, thanks for the reply. Yes, I did that too, sorry I forgot to mention that above. I just recently reinstalled Arch linux, so it is a fresh install. I don't know if this is relevant, but my laptop has only usb-c ports... but USB drives still show up as 'sd*', so I didn't think this would have any impact.

**Comment by x70b1** [comment]
Mh, at the moment it seems that there is something broken. 
For me it doesnt work too now. I will check this.

**Comment by GinGin3203** [comment]
Same problem here. Looking forward for the fix!

**Comment by x70b1** [comment]
Its still on my list. :+1:

**Comment by flamendless** [comment]
> It should be the name of your script.

Which is `system-usb-dev.sh` ? (there are two system-usb script here), im using the `system-usb-dev` one, but got confused why the `rules` file there point to the `system-usb-mount.sh` which is another script. Also, doesnt work for me both

**Comment by x70b1** [comment]
It looks like there were changes in `lsblk`.

**Comment by x70b1** [comment]
Use the latest version of `system-usb-udev` to fix that. :sunglasses:

**Comment by BILL-BUFALO** [comment]
Need to rewrite strings like: `'.blockdevices [] | select (.type == "part") | select (.rm == true) | select (.mountpoint == null) | .name '` On actual ones, like `.rm == "1"`
I also changed the delay `sleep 60` - it's long
