### ISSUE TITLE
updates-arch-combined: a way to refresh the module

### ISSUE THREAD

**Issue by zjeffer** [x70b1/polybar-scripts#112]
For the updates-arch-combined module, I'd like to find a way to refresh the module after it has updated. Now, after updating, the module still reads the amount of updates BEFORE it has updated, because it hasn't reloaded yet (obviously).

I'd like to find a way to force it to reload after it has completed an update. Is there a way?

**Comment by x70b1** [comment]
I have no solution for that now. I use an interval of 1 minute. Thats okay fo the most cases.
