### ISSUE TITLE
[Need help] TOTP / 2 factors auth countdown

### ISSUE THREAD

**Issue by Spheerys** [x70b1/polybar-scripts#115]
Hi,

I just dreamt of a module which show a thirty seconds countdown to easily show the validity of TOTP code for the 2 factors authentification protocol.
Who never be frustrated by finishing to enter the code while the 30 seconds just expired ? Who ??
I'm using several scripts like this, which give me the code for a website :
```
#!/bin/bash

key_complete=$(oathtool --base32 --totp "U4FGXWKTUHjAU42DMQH")
key_part1=$(echo $key_complete | cut -c 1-3)
key_separator="•"
key_part2=$(echo $key_complete | cut -c 4-6)
key=$key_part1$key_separator$key_part2

echo $key
```
For now, I have to check the clock on my bottom right corner when my TOTP codes are on the top of my screen, that is not very efficient, recognized it ! 
I obviously could change the clock's position (or the codes position!!) but it is not so fun...

On my dream, I saw a graphical radar counter, but a 2-digits countdown could be very very usefull ! 
Didn't it ?

Do you thing a module like this could be usefull on 2019 ?
Is it the right place to post my help request ?
Someone here is OK to help me to realize my dream ?

**Comment by x70b1** [comment]
Open Source doesn't work because someone asks if they can do something. It works because someone starts doing cool things. 
The best way is to just start. :sunglasses:
