### ISSUE TITLE
player-mpris-tail no longer working with spotify on one machine

### ISSUE THREAD

**Issue by OxSon** [x70b1/polybar-scripts#132]
Both my desktop and my laptop are running  Arch, and for the most part, have the  same config files  (i'm  using [dotbot](https://github.com/anishathalye/dotbot).

On my desktop, the script works fine with spotify. On my laptop, if i run the script while VLC is playing something, it is able to play/pause/get metadata etc,  but still nothing shows in my  polybar.

I've noticed I do have a different version of the script on each machine. [Here is the diff](https://www.diffchecker.com/taUZKv1e). Unfortunately I don't know Python and can only guess  as to what the difference would  be.

But regardless,   replacing the file on my laptop with the one on my  desktop still does not solve the issue. I'm stumped.

**Comment by x70b1** [comment]
It seems like there are bigger problems with that script and spotify at the moment.
@Cybolic wrote it. Maybe he can help us.

**Comment by Cybolic** [comment]
Yeah, I never did get around to testing the Spotify issues out further as I don't have a Spotify subscription, but maybe we can narrow the issue down a bit with this diff.

Which version in the diff works for you? The left or the right side version?

**Comment by OxSon** [comment]
The left is my desktop which works fine, however, I changed my laptop to have the same contents and the issue persists. So at this point I'm thinking the problem is somewhere else on my machine and possibly not the fault of the script at all. 

Additional info: `playerctl` cannot detect Spotify, but does detect VLC. The script can play/pause/etc VLC when run from the command line, but nothing shows in polybar and it has no output in the console.

**Comment by Cybolic** [comment]
If you run the script as this:

```
python3 ./player-mpris-tail.py list
```

is Spotify then listed?

**Comment by OxSon** [comment]
No it's not. If I run it with VLC open but not playing anything I get:

    vlc : stopped

**Comment by Cybolic** [comment]
Alright, that gives me somewhere to start :) Are you running the official Spotify client ( / which package)?

**Comment by OxSon** [comment]
I'm running the Spotify client from Snap on my laptop and the AUR package on my desktop.

I've also tried using the AUR package on my laptop and had the same issue, though.
Versions:
 Snap: `1.1.0.237.g378f6f25`
 AUR: `1.0.98.78-2`

**Comment by Cybolic** [comment]
Hmm, that version works fine on my Arch install.

What do you get if you run:

```bash
python3 -c 'import pprint,dbus;session_bus = dbus.SessionBus();pprint.pprint([ n for n in session_bus.list_names() if "potify" in n.lower() or "mediaplayer" in n.lower()])'
```

**Comment by OxSon** [comment]
With just Spotify running: `[]` 
With VLC running as well: `[dbus.String('org.mpris.MediaPlayer2.vlc')]`

**Comment by Cybolic** [comment]
Okay, that narrows this down to the problem being with the Spotify install itself. For some reason it's not adding its MPRIS functionality to the environment.

There isn't really anything this script can do about it, unfortunately.
The only thing I can think of that might work in your case, is the dbus address fix mentioned on the Arch wiki: https://wiki.archlinux.org/index.php/spotify#MPRIS

**Comment by OxSon** [comment]
Okay,  I'll take a look. Thanks for  your time and for the info. @x70b1 it sounds  like this issue should probably be closed.

**Comment by x70b1** [comment]
What is the dbus fix?
The shell code?

**Comment by Cybolic** [comment]
Yup, the shell script. I have no idea if it works though.

**Comment by x70b1** [comment]
@OxSon What is your solution now?

**Comment by OxSon** [comment]
No solution unfortunately. I haven't gotten the script to work yet :(

**Comment by x70b1** [comment]
That means, sometimes spotify is detected and sometimes not?

@OxSon You run the snap version on your laptop and it doesnt work. 
Maybe it depends on the snap version?

@Cybolic Could you also check the other issue in `polybar-scripts` if you have some free time?

**Comment by OxSon** [comment]
I'll double check tomorrow, but I believe I tried it with both the snap package and the AUR package and had the same issue both times.

**Comment by OxSon** [comment]
Yeah, I double checked and the issue persists with both the AUR package and the snap package

**Comment by OxSon** [comment]
Update fellas: More recent versions of Spotify have fixed this problem with no other changes. Seems to me that the problem was never with the script, but with Spotify. Closed issue, perhaps?

**Comment by x70b1** [comment]
Sounds good, thank you for that feedback!
Since you are a user of spotify, can you recreate the problem in #107?
