### ISSUE TITLE
MOC script question

### ISSUE THREAD

**Issue by fwanky** [x70b1/polybar-scripts#139]
Script works great, but i'm wondering if it's possible for it to stop showing on the bar when paused? Right now I just kill the server but I wanna be able to unpause it after a while while it also not taking up uneeded space when not being used.

**Comment by x70b1** [comment]
I dont have moc installed at the moment. 
But I guess if you look at `mocp -Q %state` and it returns `stopped` then you could adapt the script.

**Comment by fwanky** [comment]
I thought about this a bit more, you think it could be possible to maybe, if paused long enough for it to hide intself?

**Comment by x70b1** [comment]
Yes, the `interval` should be short enough. If moc is paused you should only do something like `echo ""`. So you module is empty.

**Comment by fwanky** [comment]
Edit the script itself?

**Comment by fwanky** [comment]
Would I just do an if statement like this? 
 if [ "$(mocp -Q %state)" != "Pause" ];then
    echo ""

**Comment by x70b1** [comment]
What is the exact output of `mocp -Q %state`?

**Comment by fwanky** [comment]
It'll differeniate when it's playing and not, it's playing right now so the status is PLAY.

**Comment by fwanky** [comment]
https://0x0.st/zofL.png

**Comment by x70b1** [comment]
Try this:

```
#!/bin/sh

state=$(mocp -Q %state)

if [ "$state" != "STOP" ] || [ "$state" != "PAUSED" ];then
    SONG=$(mocp -Q %song)

    if [ -n "$SONG" ]; then
        echo "$SONG - $(mocp -Q %album)"
    else
        basename "$(mocp -Q %file)"
    fi
else
    echo ""
fi
```

You can change the values STOP and PAUSED, I dont know what tha output of`mocp` is exactly.

**Comment by fwanky** [comment]
I changed it to that, and changed the variables to be correct but it didn't seem to work :( 

`#!/bin/sh

state=$(mocp -Q %state)

if [ "$state" != "STOP" ] || [ "$state" != "PAUSE" ];then
    SONG=$(mocp -Q %song)

    if [ -n "$SONG" ]; then
        echo "$SONG - $(mocp -Q %album)"
    else
        basename "$(mocp -Q %file)"
    fi
else
    echo ""
fi`

**Comment by x70b1** [comment]
Can you run the script on a terminal? What is the output?

**Comment by fwanky** [comment]
Well, the script WORKS just doesn't do my idea that we talked about :(

**Comment by x70b1** [comment]
You want it to disappear when there's no song playing? Do I understand that right?

**Comment by fwanky** [comment]
When it's paused for more than a couple of minutes, basically I want for it to disappear, yeah. I may have described it wrong hah

**Comment by x70b1** [comment]
Ah okay. So you problem is that you dont have a button to start it again because the button is away?

**Comment by fwanky** [comment]
Noooo, the problem is that it doesn't do that, or does it already? It may do and I just havent seen it disappear

**Comment by x70b1** [comment]
The script in the repo should disappear when `mocp` returns `stopped`. My script in this issue should disapper if `mocp` returns `stopped` or `paused`.

What is your `interval` value in your config of your polybar module?

**Comment by fwanky** [comment]
It hasnt disappeared from what I can see, the interval is 3.
I had made it go to stop with a command but then I can't unpause it from where I was, which is what I wanted in the first place. I put how I edited the script earlier but with PAUSE it doesn't seem to disappear

**Comment by x70b1** [comment]
I dont have a moc here, so i cant test much. 

But you could take a look what `moc` returns wit `mocp -Q %state`. This should be the same value like in that condition.

**Comment by fwanky** [comment]
Yeah, I tried that with the echo "" thing. but I could never get it to work. Oh well.

**Comment by x70b1** [comment]
At the moment I have no idea whats wrong here and I cant reproduce it.
