### ISSUE TITLE
player-mpris-tail: current progress in the song

### ISSUE THREAD

**Issue by SpaceboyRoss01** [x70b1/polybar-scripts#140]
Being able to have the current progress of the song would be useful. We could see how far we're into a song.

**Comment by x70b1** [comment]
Yes, good point. You could open a PR?

**Comment by SpaceboyRoss01** [comment]
I dunno what to do to get the progress of the song so sorry, I can't.

**Comment by x70b1** [comment]
Then we should close this. :stuck_out_tongue:
