### ISSUE TITLE
MOCP

### ISSUE THREAD

**Issue by fwanky** [x70b1/polybar-scripts#142]
Is mocp supposed to show the song then the album? I would have thought it would show the artist > song name, no?
here's what I mean
https://0x0.st/zHHK.png

**Comment by fwanky** [comment]
here's what I mean 
https://0x0.st/zHHK.png

**Comment by fwanky** [comment]
bump

**Comment by x70b1** [comment]
The script is very simple. At the moment it shows song and album.
You can adapt it if you want something else. Just read the code.

**Comment by fwanky** [comment]
oh, my bad. thought it was it had something to do with the tags of the mp3 file,
how do I make it so that it shows artist, then song, then album

if i do

```
#!/bin/sh

state=$(mocp -Q %state)

if [ "$state" != "STOP" ] || [ "$state" != "PAUSE" ];then
    SONG=$(mocp -Q %song)

    if [ -n "$SONG" ]; then
        echo "$SONG - $(mocp -Q %artist)"
    else
        basename "$(mocp -Q %file)"
    fi
else
    echo ""
fi
```
then it shows the artist after the song, sorry if this is petty and easy to figure out, i know nothing about bash really

**Comment by x70b1** [comment]
Change `echo "$SONG - $(mocp -Q %artist)"` to `echo "$(mocp -Q %artist) - $SONG"`
`

**Comment by fwanky** [comment]
Yeah,

i got it working by switching out the song variable with artist and then changing album to song, but how would I add the album var right at the end? Whenver I try to add it with an if statement it seems to bork
