### ISSUE TITLE
info-softwarecounter.py - Error: process ID out of range

### ISSUE THREAD

**Issue by WyRe** [x70b1/polybar-scripts#144]
Apparently info-softwarecounter.py is not handling properly `conky` (I've not added it to `combine_guis =` or `combine_proccesses =`), actually you could find my customization [in here](https://github.com/WyRe/dotfiles/blob/master/polybar/.config/polybar/polybar-scripts/info-softwarecounter.py)

what do you think about that? 
![Peek 16-03-2019 17-09](https://user-images.githubusercontent.com/4059108/54478093-ea59b380-480e-11e9-8e05-9de20a16777b.gif)

Thank you all :+1:

**Comment by x70b1** [comment]
I am not sure whats wrong there. 
But I can't see any problems with conky. For me everything runs as expected with your script.

It looks a bit weird. You stop conky but your terminal is still clear. That shouldn't be? It should turn black. Maybe the error is somewhere else.
