### ISSUE TITLE
popup-calendar.sh position

### ISSUE THREAD

**Issue by theone29** [x70b1/polybar-scripts#145]
Hi, 
Awesome script by the way. I'm using i3-gap and I'm having a hard time trying to position the calendar under the bar where you clicked on. Can you give me some tips or info on how to go about setting it up? Thank you.

**Comment by x70b1** [comment]
What's the exact problem?
There are a number of configuration notes. You need to customize the script and modify your i3-config.

**Comment by aDogCalledSpot** [comment]
I wanted to add to this in case someone comes across the same issue. My problem was that I didn't have xdotool installed, afterwards everything worked fine.

**Comment by x70b1** [comment]
You can find this information at [popup-calendar#dependencies](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/popup-calendar#dependencies).
I don't know what we can do better here.

**Comment by aDogCalledSpot** [comment]
It's fine the way it is, I just wanted to write down the answer here for the sake of completion in case someone else runs into the issue.
