### ISSUE TITLE
player-mpris-tail script not exiting along with polybar

### ISSUE THREAD

**Issue by andersthune** [x70b1/polybar-scripts#152]
The player-mpris-tail.py process doesn't seem to exit along with polybar. It's not that big a deal as restarting polybar is pretty rare, but it seems like something that should be fixed if possible. I tried looking into it myself, but wasn't able to make much progress.

**Comment by x70b1** [comment]
I can't reproduce it.

This behavior would also be strange, because the script is executed as a subprocess by `polybar`. so it should die when `polybar` is being stopped.

**Comment by andersthune** [comment]
Ah, the issue was in my own setup. I was running polybar as a subprocess of Emacs (in EXWM) and exiting it through Emacs' own process list. It seems this was sending SIGKILL rather than SIGTERM, causing the process to exit without properly shutting down the script.

I agree, it would have been strange behaviour. I'll have to modify the Emacs command to send SIGTERM instead...
