### ISSUE TITLE
intel-nvidia laptop graphics card temperatures, for double graphics cards

### ISSUE THREAD

**Issue by medioman** [x70b1/polybar-scripts#155]
Hi, I was wondering if there is the possibility to do a script for polybar, to find intel-nvidia graphics cards, with the free nouveau and intel drivers.
thank you and sorry for the trouble

**Comment by x70b1** [comment]
At the moment we have `system-gpu-intel`, `system-nvidia-bbswitch` and `system-nvidia-smi`.

I don't have any hardware to test your setup. I also don't know what possibilities there are to get data from the graphics card.
