### ISSUE TITLE
test info-xampp

### ISSUE THREAD

**Issue by x70b1** [x70b1/polybar-scripts#19]
@TetrisIQ

I updated `info-xampp`. Could you test it? 

Why do we need the Troubleshooting section? We read the informations from the `status` command. Is this not availiable if we don't patch MySQL?

**Comment by TetrisIQ** [comment]
We need the Troubleshooting: in my case I cannot read the status look here:  ![img](http://i.imgur.com/75tiMlK.png)
I Tested the script and made some changes, so it should work fine now.

**Comment by x70b1** [comment]
Okay, I install XAMPP and test it.
