### ISSUE TITLE
info-redshift-temp illegal number

### ISSUE THREAD

**Issue by mrneilypops** [x70b1/polybar-scripts#23]
I am trying to get this script to work but it complains of an illegal number...

[mrneilypops@void polybar-scripts]$ ./info-redshift-temp.sh
./info-redshift-temp.sh: 8: [: Illegal number: :
./info-redshift-temp.sh: 10: [: Illegal number: :
%{F#D08770} #

**Comment by x70b1** [comment]
There is already a fix in PR #22. Is this the same problem?

**Comment by mrneilypops** [comment]
OK-I think that was the problem-thanks!

**Comment by x70b1** [comment]
I wrote a new comment in the PR. If you like you could review my suggestion and comment.
