### ISSUE TITLE
battery-combined-udev - Line 38 Division by 0 Error

### ISSUE THREAD

**Issue by matcharles** [x70b1/polybar-scripts#25]
Hello, I am trying to get this to work but I am having issues with the script. When I try to run it, I get the following error:

`./battery-combined-udev.sh: line 38: 0 / 0: division by 0 (error token is "0")`

I have changed the relevant location in line 67 as per the readme file. I have very limited knowledge in programing, so don't know where to start to troubleshoot. FYI, I have the same error with the verison batter-combined-shell.

Thanks a lot for your time!

**Comment by x70b1** [comment]
Do you have two batteries installed or just one?

**Comment by matcharles** [comment]
I have only one. BAT0 (and AC)

**Comment by x70b1** [comment]
Is there a reason why you dont use the build-in module? It should be better in this case. 

What happens if you replace line 37 and 38 to:

```sh
battery_percent=$(("$battery_level_0 * 100"))
battery_percent=$(("$battery_percent / $battery_max_0"))
```

**Comment by matcharles** [comment]
I am getting the same output by changing those lines.

As for the reason, I never had any problem with the default one but since the last compile, I received this error with the default module:

`error: module/battery: std::bad_alloc
warn: Stopping 'module/battery'...
`

**Comment by x70b1** [comment]
They have problems at the moment. But it seems fixed. 
https://github.com/jaagr/polybar/issues/985

I can later take a look what is wrong in my script with only one battery.

**Comment by matcharles** [comment]
Thanks for pointing me in the right direction, the latest commit did in fact fix the issue. Let me know if you want me to help you testing your script, otherwise you can close it.

**Comment by x70b1** [comment]
Sounds good. 
I will close this issue. It was developed for two batteries, as the built-in module is probably better for one battery.

**Comment by SpamixOfficial** [comment]
Hello! I'm having the exact same issue. Here's my output:
```
./battery-combined-udev.sh: line 38: 0 / 0: division by 0 (error token is "0")
```

**Comment by x70b1** [comment]
And you use two batteries?

**Comment by SpamixOfficial** [comment]
Actually, no. I don't. Do I need 2 batteries for it to work?

**Comment by x70b1** [comment]
The script can only find one battery. The result is your error because we calculate a value over two batteries there. 

The [internal battery module](https://github.com/polybar/polybar/wiki/Module:-battery) is probably a better idea if you only have one.
