### ISSUE TITLE
pulseaudio-tail speed improvement (?)

### ISSUE THREAD

**Issue by Kalagon** [x70b1/polybar-scripts#27]
Hey, it might be my imagination and bias but I think restructuring the loop in `pulseautio-tail` can have noticeable effects on performance. I built it like this:
```shell
listen() {
    volume_print

    pactl subscribe | grep --line-buffered "sink" | while read -r e; do
        volume_print;
    done
}
```
This reduces the amount of data that is processed, at least as long as there is no non-default sink going crazy.

**Comment by x70b1** [comment]
The problem is that you have to pay attention to different translations. If you use another language, your command will no more work. I already had the same idea.

**Comment by Kalagon** [comment]
Uuuh, yeah. I just noticed that this will also trigger on sound events. I'll experiment with it a bit more.

**Comment by Kalagon** [comment]
Well, if being language-agnostic is the only issue, grepping on "#$sink", like it was before, should be fine.

**Comment by x70b1** [comment]
I know it is not 100% perfect but the impact should be very low. I think at this point user comfort goes over performance. The scripts should run out of the box. 

Anyway, thanks for your idea!
