### ISSUE TITLE
Add documentation on changing icons

### ISSUE THREAD

**Issue by Cybolic** [x70b1/polybar-scripts#29]
The README currently states: 

> Use # or #1, #2 .. as icon replacement in your scripts. Everyone use anoter icon font. So let the user decide which icon he wants to use.

but doesn't provide information on how the user should replace these strings with their desired icons (and as far as I can tell, neither does the polybar documentation).

Adding this information would be helpful to new users.

**Comment by x70b1** [comment]
The point is simply that there are many icon fonts. A small selection can be found here: [jaagr/polybar/wiki/Fonts#icon-fonts](https://github.com/jaagr/polybar/wiki/Fonts#icon-fonts)

Everyone wants to customize their system and use the icons they like. So I don't want to predefine anything. It's not difficult at all. All `#` in the code are icons that are printed. These have to be replaced. gucharmap is a good tool to find the symbols in the font.

**Comment by Cybolic** [comment]
Thanks for the explanation. Unfortunately, I'm still not sure how to replace the icons; are they meant to be replaced manually in the scripts or is there a configuration option in the polybar config that lets one replace them dynamically?

**Comment by x70b1** [comment]
Simply copy and paste. :v:

**Comment by Cybolic** [comment]
Thanks :) Maybe this is worth adding to the documentation? Something along the lines of:
> If you are just looking for a way to set your own icons, simply replace the appropriate icon strings in the script (e.g. replace `#1` with `🎉`).

**Comment by x70b1** [comment]
Yeah, I will do that. 
If you need more help configuring polybar-scripts, join #freenode. I hang out there. :alien:
