### ISSUE TITLE
player-mpris-tail no output

### ISSUE THREAD

**Issue by ibrokemypie** [x70b1/polybar-scripts#35]
Hey, when trying to use player-mpris-tail I simply get no output in my bar. Playerctl itself correctly shows my players and the current status, but even running the script manually does nothing. I am on arch linux with python up to date.

**Comment by x70b1** [comment]
Can you paste the needed parts of your config?

**Comment by ibrokemypie** [comment]
```
[module/player-mpris-tail]
type = custom/script
exec = ~/.config/polybar/player-mpris-tail.py
tail = true
click-left = ~/.config/polybar/player-ctrl.sh previous
click-right = ~/.config/polybar/player-ctrl.sh next
click-middle = ~/.config/polybar/player-ctrl.sh play-pause
```

**Comment by x70b1** [comment]
And you added `player-mpris-tail` to your bar?
Like `modules-right = player-mpris-tail`

**Comment by ibrokemypie** [comment]
Yes, I did

**Comment by x70b1** [comment]
You are right. I have the same problem here on Fedora. The script run but there is no output.

```
$ python3 -V
Python 3.6.4
```

Unfortunately I do not use a player script. So I have not much experience with it.
Maybe @Cybolic can help. He was the last one who worked on this script. Let's give him some time to answer.

**Comment by Cybolic** [comment]
Maybe it's a case of missing packages; I added a call to `dbus-send`. Could you check if that command is available on your system?

**Comment by x70b1** [comment]
`dbus-send` is available.

I checked that on my Arch device. It works if I install `playerctl` and `playerctl-git`. 
It's a little bit weird. It works on my Fedora now too. But I haven't changed anything.

@ibrokemypie could you find out something?

@Cybolic should we add `python-gobject` as dependency? Otherwise I got an error:

```
python3 polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py 
Traceback (most recent call last):
  File "polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py", line 8, in <module>
    gi.require_version('Playerctl', '1.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

**Comment by Cybolic** [comment]
Yes, I think that would be a good idea.
Outside of this issue, I'd like to revisit the script at some point and do a rewrite as it's still not great at handling multiple players and can be redone to not actually need `playerctl` (or `dbus-send` for that matter). Unfortunately, I'm swamped with work these days, but I do expect to get on it within a month or so.

As for solving this, with your player open, what do you get when running the following?

```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2
```

**Comment by x70b1** [comment]
```
string "org.mpris.MediaPlayer2.rhythmbox"
```
That is my output. 

No hurry. As long as everything works, here is not much to fix. I don't think the dbus is the problem. I guess it is the existing script. It looks a bit unstable. Multiple players use different keys.

**Comment by ibrokemypie** [comment]
I have both playerctl and dbus-send
```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2

      string "org.mpris.MediaPlayer2.cmus"

```

**Comment by nealot** [comment]
I'm having the same problem; anyone know of any workarounds? Here is my output:
```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2

      string "org.mpris.MediaPlayer2.mps-youtube.instance2283"
```

**Comment by Cybolic** [comment]
I've finally gotten a bit of time to look at the rewrite and I have the status part up and running well enough to use it for my own daily use. If anyone wants to try it out, use the following script instead of the one in `exec = ~/.config/polybar/player-mpris-tail.py`

https://gist.github.com/Cybolic/3ad51365f0d329b0ac2bc177ea721af5

This one doesn't have any dependencies other than the python dbus module.

**Comment by Cybolic** [comment]
Meaning a script that will provide the functionality of `player-ctrl.sh` when given the appropriate arguments? That's on my roadmap :)

**Comment by x70b1** [comment]
So that you have to install just one script.

You are the man and this is your script. :beer:

**Comment by Cybolic** [comment]
I've updated the script in the link so it now supports the basic playback controls that playertrl does (minus seek, volume and getting metadata/status). I'd be grateful if people could try this out and see how it works for them so I can get an idea of how far we are from this replacing the current script.

**Comment by nealot** [comment]
What would be the default module configuration for it?

**Comment by nealot** [comment]
What would be the default module configuration for it?

**Comment by Cybolic** [comment]
@nealot I'm running it as follows:

```
[module/player-mpris-tail]
type = custom/script
exec = ~/INSERT_DOWNLOAD_PATH_HERE/player-mpris-tail2.py
tail = true
label = %output:0:60%...
click-left = ~/INSERT_DOWNLOAD_PATH_HERE/player-mpris-tail2.py previous
click-right = ~/INSERT_DOWNLOAD_PATH_HERE/player-mpris-tail2.py next
click-middle = ~/INSERT_DOWNLOAD_PATH_HERE/player-mpris-tail2.py play-pause
```

**Comment by nealot** [comment]
@Cybolic Thanks! But I can't seem to get it working. I'm using https://github.com/mps-youtube/mps-youtube and it only displays the closed icon.

**Comment by x70b1** [comment]
> For mpris2 support, install the python bindings for dbus and gobject:
> `$ pip3 install --user dbus-python pygobject`

**Comment by nealot** [comment]
I have the module already installed but some songs aren't being recognized. Does the script only work if an artist is specified? Because mpsyt sometimes only lists the title.

**Comment by nealot** [comment]
```
if len(self.metadata['artist']) and (self.metadata['title']):
```
This seems to be the suspect line.

**Comment by Cybolic** [comment]
I've updated the script again to remove the restriction on the artist and added the blacklisting as well as formatting (with conditional text), so you can run it as this:
`player-mpris-tail2.p --blacklist plasma-browser-integration -b vlc -f '{title}{:album: on {album}:}{:year: ({year}):}{:artist: by {artist}:}'`
which will leave plasma-browser-integration and vlc alone and print the status with the ` on {album}`, ` (year)` and ` by {artist}` parts only if the album, year or artist tags aren't empty respectively.

**Comment by Cybolic** [comment]
Updated the script:
- Select the current player better, based on it's play-status
- Added new commands: `list`, `current` and `metadata`
- Fixed empty tags being regarded as existing (for conditional formatting)

I think it's pretty close to being able to replace the old script; has anyone had any issues?

**Comment by nealot** [comment]
Is the script supposed to know if the application has been closed? When I open mpsyt and then exit it just keeps the last output it had.

**Comment by Cybolic** [comment]
@nealot It is supposed to detect that, yes, but it'll keep showing the last status (useful for when paused). I'll see about properly detecting when nothing is active and clear the output when that happens.

**Comment by Cybolic** [comment]
@nealot Your issue should be fixed with the latest update. I've also added options to set the icons used, improved performance a bit by not updating text when only the seek position has changed and fixed a few silly copy-paste errors that kept stop/previous/next from working.

**Comment by nealot** [comment]
Everything works well for me now :+1:. Also, I prefer the icon layout below so if anyone else shares this preference they could use:
```
exec  = player-mpris-tail2.py -f '{:artist:{artist} - :}{title}'
label = %output:0:30: . . .% %{A1:playerctl previous:}%{A} %{A1:playerctl play-pause:}%{A} %{A1:playerctl next:}%{A} 
```
![screenshot_20180830_222157](https://user-images.githubusercontent.com/36805289/44889264-21b5a800-aca3-11e8-9c13-09f001c6f4e7.png)

**Comment by Cybolic** [comment]
Okay, I may have gone overboard with handling your case @nealot :stuck_out_tongue: 

I extended the formatting handling to not touch Polybar's syntax so you can pass it directly, and also added basic width handling for the fields as the second "part" of the format block (or the first if we don't want it conditional).

i.e.:
`{:w10:text:}` to crop the `text` to 10 chars
`{:t10:text:}` to truncate the `text` to 10 chars, appending `...` to it if it's longer than that
This also works with conditional tags: `{:artist:w10:{artist} - :}` or `{:album:t10: - {album}:}`.

I also added a tag for a reversed icon that shows the pause icon when playing and the play icon at all other times.

For your case, that means you can do the following:
```
exec  = player-mpris-tail2.py -f '{:artist:t12:{artist}:}{:artist: - :}{:t15:{title}:} %{A1:playerctl previous:}%{A} %{A1:playerctl play-pause:}{icon-reversed}%{A} %{A1:playerctl next:}%{A}'
label = %output%
```

**Comment by nealot** [comment]
That's actually awesome -- thank you!

**Comment by Cybolic** [comment]
You're welcome! I've adopted a version of your label now myself, so I definitely got something out of it as well :wink: 

I'll keep running with this for a few days and if no new issues pop up here or on my machine, I'll document the formatting and send a pull request.
