### ISSUE TITLE
openweatherapp: not showing

### ISSUE THREAD

**Issue by pat-s** [x70b1/polybar-scripts#36]
https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/openweathermap-fullfeatured

* API key installed
* Weather icon font is loading properly 
* Font assigned as `font-10` and refered in module setting as `label-active = 11`
* jq installed
* no errors when tracing `l- info`

Anything I am missing?

**Comment by x70b1** [comment]
What does the Script if you run it in your shell?
Does it work? Or are there errors?

**Comment by davidv171** [comment]
Same here. No error logs. Just nothing showing up. I've got the fonts and jq. No permission errors either.

Owned and executed by the user. Is this where I'm doing wrong?

**Comment by x70b1** [comment]
What happens if you run that script in your shell?

**Comment by davidv171** [comment]
Just stops. no output. Maybe should say that the simple version of the script did the same thing so it might be not specific to the script but my set-up. I'm new at this.

**Comment by x70b1** [comment]
You could write a `set -x` at the top of your script. But not at the top of `/bin/sh`.
The script shows you excatly what it did.

**Comment by davidv171** [comment]
Oh my city ID was missing. The output is kinda messed up though. 
http://i.imgur.com/iTXOVOV.png

**Comment by x70b1** [comment]
`set -x` prints the output of everything. Yes, that can be much.
What is on the pic? Your api-key?

Does everything work now?

**Comment by davidv171** [comment]
It works. The pic was my api-key I guess. It works but I'm kind of confused on what the icons are. There were just 2 crosses and the icon for a mounted system? Is that a font issue? Editing the upper comment to remove my api-key from plain sight.

**Comment by x70b1** [comment]
You delete your key now :wink:

Looks like font-issue. I guess you have to set up `weather-icons`.
