### ISSUE TITLE
Specify City ID required or switch to `?q=$CITY`

### ISSUE THREAD

**Issue by roguh** [x70b1/polybar-scripts#45]
I found it unclear that the `openweathermap-fullfeatured.sh` and `openweathermap-detailed.sh` scripts need a city ID as the `CITY` parameter. I'd prefer to see this indicated in the README or in a comment. Alternatively, we could use `q=$CITY` instead of `id=$CITY`.

**Comment by x70b1** [comment]
So you tried `CITY="Berlin"`?

**Comment by roguh** [comment]
Hello! First off, thank you for your great work.

When I access [http://api.openweathermap.org/data/2.5/forecast?APPID=6f9b0c20232eb046ec3d0328fefefd40&id=Berlin&units=Imperial&cnt=1](http://api.openweathermap.org/data/2.5/forecast?APPID=6f9b0c20232eb046ec3d0328fefefd40&id=Berlin&units=Imperial&cnt=1), I receive the following JSON response:

```{"cod":"400","message":"Berlin is not a city ID"}```

By changing `id=$CITY` to `q=$CITY`, I receive the correct JSON response for `CITY="Berlin"`.

**Comment by x70b1** [comment]
Thanks a lot!

Yes. `CITY` is actually misleading. I should fix that with a comment in the docs.
The City ID for Berlin is `2950159`. That would be the needed ID for `CITY`.

You should drop your API-Token now. :wink:

**Comment by roguh** [comment]
Thank you! Almost forgot my API token...
