### ISSUE TITLE
openweathermap: Add details about which icons to use

### ISSUE THREAD

**Issue by nhatzHK** [x70b1/polybar-scripts#59]
It's said in the main README to replace icons strings by the appropriated ones, but there is no way to tell which ones are appropriate. All over the scripts (I'm guessing) placeholder icons are used but there is no instructions on what they are supposed to represent.

Anyway I really like this :+1: 

EDIT: I have installed the required font already, I just don't know what to replace the boilerplate icons with.

**Comment by szymonmaszke** [comment]
openweathermap icons should work out of the box (granted you have installed the font). Have you specified the font in your polybar ```config```?

**Comment by 132ikl** [comment]
The openweathermap scripts don't use the boilerplate icons. They have the correct icons already. Make sure you specified the font in your config and set the module to use that font.

**Comment by nhatzHK** [comment]
Just to be sure I'm not missing something, are you referring to the icons in this function?
```sh
get_icon() {
    case $1 in
        01d) icon="";;
        01n) icon="";;
        02d) icon="";;
        02n) icon="";; # cloud
        03*) icon="";;
        04*) icon="";;
        09d) icon="";;
        09n) icon="";;
        10d) icon="";;
        10n) icon="";;
        11d) icon="";;
        11n) icon="";;
        13d) icon="";;
        13n) icon="";;
        50d) icon="";;
        50n) icon="";;
        *) icon="";
    esac

    echo $icon
}
```
N.B: I Changed the one with the comment manually.

I also installed the weather icon fonts and specified them to be used in my polybar configuration.

The icons in the script look like this to me 
![image](https://user-images.githubusercontent.com/22325100/42261412-2f4ebb04-7f36-11e8-8b91-ab930f71c757.png)

**Comment by 132ikl** [comment]
It looks like the font config is slightly off. For example, if you have weather icons as font 2, you have to use label-font = 3 in settings. Try that.

**Comment by nhatzHK** [comment]
That worked, thank you.

I have the font as 5, when I used 6, I saw the icons properly.

:+1:

**Comment by nhatzHK** [comment]
I'm proposing to rename this to reflect the problem that created it and close it.

**Comment by 132ikl** [comment]
added [https://github.com/jaagr/polybar/issues/1305](polybar#1305)
