### ISSUE TITLE
Merge similar versions

### ISSUE THREAD

**Issue by alexozer** [x70b1/polybar-scripts#6]
I understand it might be tedious, has merging similar versions of scripts together been considered? For example, if all openweathermap scripts were merged into a single script (with differences in functionality toggleable with options), it would deduplicate a lot.

**Comment by x70b1** [comment]
You're right. That is an interesting point. 

But what could be the solution?  We could merge all the scripts. And the output can then be build up by the user using different variables in a string. 

However, many calculations would then be made that are never necessary. Polybar is lightweight. I think the scripts should be the same and only calculate what is needed. 

Therefore, my suggestion for a solution is this: If no location is set, it is queried via the Mozilla API. We build a sample code and customize all scripts.
