### ISSUE TITLE
Question about openweather scripts

### ISSUE THREAD

**Issue by vaskark** [x70b1/polybar-scripts#65]
I'm just wondering why the weather icons in Symbols Nerd Font don't work, and I have to add the Weather Iconsfont  declaration to my polybar config file. Are the codes different?

Thanks. And thanks for all the scripts :)

**Comment by 132ikl** [comment]
Yes, the codes are different. If you really wanted to, you could manually replace the icons in the script to the Nerd Fonts variant, but that would be extremely tedious.

**Comment by x70b1** [comment]
You can replace the icons in your `get_icon` function.
I guess the icons in Nerd Fonts have different codes so they don't work as drop in.
