### ISSUE TITLE
change weather text font/size

### ISSUE THREAD

**Issue by mrneilypops** [x70b1/polybar-scripts#67]
How can I change the size of the text associated with each weather icon?
Ideally, I would like to use ohsnap font...

**Comment by x70b1** [comment]
This depends on your font setting. In the example you have font size 12.
Check the polybar docs to find out how to setup your fonts.

```
[bar/polybar]
...
font-2 = Weather Icons:size=12;1
...
```

Does the ohsnap font support weather icons?

**Comment by mrneilypops** [comment]
I know how to change the font size but my problem is that the numerical text that reports the temperature does not change in size. Also, I would prefer this text number to be a different font eg. ohsnap
You see in the scrot that my polybar has ohsnap fonts...I would like to have the same 'font for the weather temperature numbers.

![2018-07-29-172658_1920x1080_scrot](https://user-images.githubusercontent.com/1450448/43367905-de8076da-9354-11e8-9a47-176201d0fa37.png)

https://scrotlabs.org/images/2018/07/29/2018-07-29-172658_1920x1080_scrot.png

**Comment by x70b1** [comment]
Can you paste ypur font config?

**Comment by mrneilypops** [comment]
not sure which file you require...
`bar/master]
width = 100%
height = 24
border-size = 0
border-top-size = 0
border-bottom-size = 1
radius = 0
bottom = false
line-size = 2
# font-0 = "DejaVu Sans Mono:size=10:antialias=false;2"
font-0 = "Misc Ohsnap:size=20:antialias=false;2"
font-1 = "Font Awesome 5 Brands:pixelsize=11;1"
font-2 = "MaterialIcons:size=12:antialias=false;2"
font-3 = "icomoon:size=10:antialias=false;2"
font-4 = "Ubuntu Nerd Font:size=10:antialias=false;2"
font-5 = "Weather Icons:size=10:antialias=false;1"
font-6 = "Misc Ohsnap:size=6:antialias=false;2"
offset-x = 0
offset-y = 0
fixed-center = true
border-color = ${colors.border}
background = ${colors.background}
foreground = ${colors.foreground}
module-margin = 0
padding-right = 0
padding-left = 0
separator = │`

**Comment by x70b1** [comment]
Set openweathericons to the last position in your font list. 
After that set `label-font = XX` in your weather module config. `XX` is the id of your openweathericons font.
