### ISSUE TITLE
updates-arch-aur,updates-arch-combined: yay displays wrong value

### ISSUE THREAD

**Issue by x70b1** [x70b1/polybar-scripts#81]
If there is no network connection, yay produces an error output which leads to a wrong value. 
There is an open issue at yay: [#715](https://github.com/Jguer/yay/issues/715)

**Comment by x70b1** [comment]
A workaround for the moment 

```
#!/bin/sh

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ping -n -c 1 -W 1 archlinux.org > /dev/null; then
    if ! updates_aur=$(yay -Qum | wc -l); then
        updates_aur=0
    fi
else
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$updates" -gt 0 ]; then
    echo "  $updates"
else
    echo ""
fi
```

**Comment by Morganamilo** [comment]
Maybe a better work around is just to check the return status. Yay will return non 0 in case of error.

**Comment by Morganamilo** [comment]
Reading the script it seems a little over engineered. Wouldn't something like this work?

```sh
#!/bin/sh
updates="`checkupdates 2> /dev/null; yay -Qum 2> /dev/null`"
if [ -n "$updates" ]; then
	echo "# $(echo "$updates" | wc -l)"
else
	echo
fi
```

Also I don't get why you' want to print an empty line with no updates or prefix the updates with `#  `. Personally I would just echo the number if it exists and that's it.

**Comment by x70b1** [comment]
You're right, checking the return code is a much better idea. 
I fixed that above. Thanks!

Polybar has a "special" behavior. If you want to delete text from it, you need to print nothing. Otherwise, if you just quit the script, the old output would be still on the bar. This means that you could update your system, but the notice on your bar would not be hidden.

The `#` sign is just a placeholder. Most users replace it with symbols from a symbol font.

**Comment by frebib** [comment]
I feel like everyone is over-complicating it, this is what I'm using:

```ini
[module/updates]
type = custom/script
exec = count=$((checkupdates & cower -u) | wc -l); test $count -gt 0 && echo $count || false
interval = 60
format-prefix = "  "
format-prefix-foreground = ${colours.icon}
click-left = i3-msg exec i3-sensible-terminal -r i3blocks-update-term -e yay
```

Of course if you're using yay, swap out `cower -u` with `yay -Qu`

This has the one added advantage that I've seen over most which is that repo and AUR updates are fetched at the same time making the block update quicker.

**Comment by 132ikl** [comment]
@frebib The entire point is that `yay` displays an error when there is no network connection, and your solution fix that.

**Comment by frebib** [comment]
Yay stderr issue resolved, does this work now?
