### ISSUE TITLE
Polybar player-mpris-tail has some issues with spotify

### ISSUE THREAD

**Issue by ShiroUsagi-san** [x70b1/polybar-scripts#82]
Hey,
It seems that your module has trouble with spotify because the dbus response is slightly different that other ones:

+ first, `xesam:length` is renamed by `mpris:length` and this is the same thing for artUrl.
+ there are netheir `xesam:contentCreated`, a date or `xesam:genre` in the dbus response.
I've fixed the first point but not the second.

~~And also, do you know what is the mpris:length? because it doesn't seems to be a duration or something.~~ This the duration in microseconds (?) my bad.

Thanks for the pretty module

**Comment by x70b1** [comment]
Thanks!

@Cybolic, Some thoughts?

**Comment by Cybolic** [comment]
I'll take a look. Thanks for the detailed report!
