### ISSUE TITLE
Merging the openweathermap-* modules into a single configurable module

### ISSUE THREAD

**Issue by dkasak** [x70b1/polybar-scripts#92]
I just made some improvements to the openweathermap-* modules and it was more tedious than necessary because they are four separate modules. As it is now, the modules share most of the functionality, with the primary difference being in what gets output in the end. 

Perhaps it would make sense to merge all of these into a single module and add one or two additional configuration variables so they can share the code?

**Comment by x70b1** [comment]
We had this idea already here: PR https://github.com/x70b1/polybar-scripts/pull/8
I closed this as wontfix. 

I'm still of the same mind. I don't want to overengineer simple and working scripts. 

But you have some good improvements in it. HTTPs requests for example.

**Comment by dkasak** [comment]
Ah, sorry, I forgot to search closed issues.

I do still think merging them would be better in this instance, but I understand your position. Closing.

**Comment by x70b1** [comment]
Thanks! 

Would you like to open a PR for your HTTPs changes? 
Otherwise i would do this.

**Comment by dkasak** [comment]
@x70b1 Do you mean a separate PR which doesn't include the city-by-name change?

**Comment by dkasak** [comment]
Of course, it might lead to the wrong city in some rare situations, but I think
the chances of that are minimal if the user also specified the country code.

The reason I added it is that I travel a lot, so I tend to change the location
a lot (Mozilla's location service doesn't give very accurate results as
currently implemented, sometimes completely missing the city by ~250 km). In
this situation, using IDs is a bit unwieldy... Of course, I could populate my
script with several entries, such as

```
CITY=<id1>  # <CITY1>
CITY=<id2>  # <CITY2>
CITY=<id3>  # <CITY3>
```

and then comment/uncomment all but one of those based on my location. However,
I thought specifying the city by name was a nice addition, particularly because
it is so easily implementable.

But again, if you're not interested in the feature, don't feel pressured. I'll
probably just commit a modified version of the script to a private repo.

I'll make a separate PR for the HTTPS API.
