### ISSUE TITLE
IMAP Shell + .netrc and POP3 Shell + .netrc

### ISSUE THREAD

**Issue by 132ikl** [x70b1/polybar-scripts#98]
There are two nearly identical scripts for IMAP and POP3, one using .netrc rather than user/pass in command. What case scenario would the first one be used over the second. Unless there is some specific purpose I'm missing, it seems redundant to offer two nearly functionally identical scripts.

**Comment by x70b1** [comment]
For security reasons it makes sense not to provide login data when starting scripts. 

The process list is readable by all users. So also the login data. A malicious program could read the process list and would get access to the data.

This can be prevented by using the `.netrc` file.

**Comment by 132ikl** [comment]
I understand that. Using that rationale, why should the non-.netrc scripts exist? If there is confusion on how to create a .netrc we can provide a small sample or tutorial on how to set one up.

**Comment by x70b1** [comment]
That's just how it's grown. 
First I wrote the script without `.netrc`. Then the one with `.netrc`.

There is a netrc file as an example. I don't know how we can do that better. Copy. Paste. Change the values.

But we could drop the scripts without `.netrc`.

**Comment by 132ikl** [comment]
I didn't see the .netrc, that's fine. Maybe drop the `netrc` suffix from the script naems?

**Comment by x70b1** [comment]
The `.netrc` is in the same dir: [polybar-scripts/inbox-imap-shellnetrc/.netrc](https://github.com/x70b1/polybar-scripts/blob/master/polybar-scripts/inbox-imap-shellnetrc/.netrc)
